### ISSUE TITLE
Ryley - 2 User Stories

### ISSUE THREAD

**Issue by bcu8** [bcu8/CS386-C-Code-Formatter#14]

**Comment by rnf45** [comment]
**User Stories**

“As a grader for a C program class, I would like to easily give feedback and suggestions for the student’s code formatting so that they are able to fix their mistakes and create more readable code.”
Priority: 7, estimated hours: 8
“As a student programmer, I want an environment where I can easily upload code to be quickly checked for bad formatting so that I can fix bad practices without searching through every line of code myself.” 
Priority: 5, estimated hours: 6
